- hosts: demo
  tasks:
    - name: Upload public authorized key
      authorized_key:
        user: pi
        state: present
        key: "{{ lookup('file', '../private-files/ansible_ssh_key.pub') }}"